### ISSUE TITLE
Move to Python 3

### ISSUE THREAD

**Issue by TingPing** [flathub/org.freedesktop.GstDebugViewer#2]
Looks like this was ported to Python 3 upstream: https://cgit.freedesktop.org/gstreamer/gst-devtools/commit/debug-viewer/GstDebugViewer?id=e557b5326d74e438325cbd0afc397a40eae4a8df

Moving to it drops most of the bundled deps here.

**Comment by thiblahute** [comment]
Yeah, we should wait for Gst 1.16 before updating.

**Comment by philn** [comment]
Ping? ;) Also updating to the 3.36 runtime would be nice! Do you want a PR for that?
